const express = require("express")
const router = express.Router()
const adminController = require('../controller/adminController')
router.post("/createAdmin",adminController.createAdmin)
router.get("/getAllUsers",adminController.getAllUsers)
router.get("/getUserById/:id",adminController.getUserById)
router.get("/getAllPvHistory",adminController.getAllPvHistory)
router.get("/countUsersByRole/:roleId",adminController.countUsersByRole)
router.get("/countUsers",adminController.countUsers)
router.delete("/deleteUser/:id",adminController.deleteUser)
router.get("/getDechetCount",adminController.countPvDechet)
router.put("/update/:adminId",adminController.UpdateProfileAdmin)
router.post("/CreateUser",adminController.createUser)
module.exports=router